[package]
name = "mutable_batch_lp_fuzz"
publish = false
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[package.metadata]
cargo-fuzz = true

[dependencies]
hashbrown = "0.14"
libfuzzer-sys = "0.4"
mutable_batch_lp = { path = ".." }
mutable_batch = { path = "../../mutable_batch" }
partition = { path = "../../partition" }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }

[[bin]]
name = "lines_converter"
path = "fuzz_targets/lines_converter.rs"
test = false
doc = false
